site_name: BlueOS Documentation
site_url: https://blueos.aloyce.com/
theme:
  name: material
  palette:
    primary: black
    accent: blue
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy


plugins:
  - search
  - blog
  - tags:
      tags_file: tags.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Pubic Hair:
    - my first one: lebron/code.md
  - About: 
    - lapibi: Pubert/cutie.md
    - chung: Pubert/steven.md
  - Tags: tags.md
  - Blog: 
    - blog/index.md